### ISSUE TITLE
Should we onboard more clubs now?

### ISSUE THREAD

**Issue by jonleung** [hackedu/discussions#8] opened 2015-04-20 16:54 UTC
I don't think it makes sense to spend this much time and just wait till later in the summer UNLESS there are SF based clubs. This is distracting for @MaxWofford from creating better clubs experiences and building the club in a box.

@zachlatta  thoughts?

**Comment by zachlatta** [comment] 2015-04-20 16:57
How long is the typical onboarding process? If it's blocking, we shouldn't do it. Just feels odd to turn down our users.

**Comment by MaxWofford** [comment] 2015-04-21 06:31
@zachlatta I agree that we shouldn't be turning down users at this stage. Maybe waitlisting, or finding ways for our existing clubs to help with some part of the onboarding process.

**Comment by zachlatta** [comment] 2015-04-21 14:06
@MaxWofford how long does it take to onboard a new club? Is it the
actual time itself spent onboarding that is blocking? Or is it all of
the coordination involved that's blocking?

**Comment by MaxWofford** [comment] 2015-04-21 22:11
I feel like we're not giving our onboarded clubs any value this late in the year. This might be something to contact our recent applicants about, and get their input on.

**Comment by zachlatta** [comment] 2015-04-23 20:07
What's the disadvantage of onboarding more?

**Comment by jonleung** [comment] 2015-04-23 21:17
Max's time can be dedicated to building the club in a box.


—
Sent from my mobile–apologies for brevity and any typos!

hackedu.us | 610-761-0083

**Comment by jonleung** [comment] 2015-04-23 21:18
And build a more automated onboarding process.


—
Sent from my mobile–apologies for brevity and any typos!

hackedu.us | 610-761-0083

**Comment by jonleung** [comment] 2015-04-24 01:39
Yeah, @MaxWofford, I personally think it would be more impactful to work on the club in the box and not onboard any more people and tell the potential new club leaders the situation that we'll poke them in the summer (unless they have an existing bay area club). 

Because if max works on the introductions, it takes him C work per introduction. However, by doing that C work, it doesn't have any net result except for this one off instance.

However, if max worked on the onboarding process for clubs in general, it can be used for a long time to onboard these clubs. So that's why I think Max should work on the general club in a box scalable solution instead of manually onboarding each club right now.

Not sure if I articulated this well @zachlatta @MaxWofford

**Comment by MaxWofford** [comment] 2015-04-24 01:53
I followed that @jonleung :)

This will likely only be actionable once I get back on the 6th and can start planning out how to rework the on-boarding process.

**Comment by jonleung** [comment] 2015-04-24 01:59
Sweet, just responding more to @zachlatta on this one!

**Comment by zachlatta** [comment] 2015-04-27 07:10
Awesome--sounds good!

@MaxWofford - before we close this issue, can you make sure our clubs spreadsheet (https://docs.google.com/spreadsheets/d/1ir-DGpLsU2-8VifomVR1XfRvoHyUIjz2rV5ab7CMDoc/edit) is completely updated with all of the new clubs? Once we've confirmed this, we can go ahead and close the issue.

**Comment by MaxWofford** [comment] 2015-04-27 14:25
@ZachLatta I'm keeping everything in a calc.hackedu.us; the google doc has notes and references that  should probably be discussed in person before I edit it.

**Comment by jonleung** [comment] 2015-04-29 18:06
Hey Max, can you link to this in a place on the github repos where we can
see it? Perhaps in meta?

Thanks!


—
Sent from my mobile–apologies for brevity and any typos!

hackedu.us | 610-761-0083

**Comment by zachlatta** [comment] 2015-04-30 14:04
@MaxWofford do you think it makes the most sense to have this on https://calc.hackedu.us? Can't anyone edit it? And would it have revision history?

**Comment by MaxWofford** [comment] 2015-05-03 06:07
@jonleung Do we want this public? It has contact info for all our leaders.

**Comment by MaxWofford** [comment] 2015-05-03 06:08
@zachlatta I'm not sure about where we want the finalized version of this to go, but I'm planning on building it up in calc.hackedu and exporting csv to something else.

**Comment by zachlatta** [comment] 2015-05-03 19:15
> @jonleung Do we want this public? It has contact info for all our leaders.

We should keep the clubs spreadsheet private. We don't want to publish our club leaders' information without their approval.

> @zachlatta I'm not sure about where we want the finalized version of this to go, but I'm planning on building it up in calc.hackedu and exporting csv to something else.

I'm not sure if I'm comfortable having this data in https://calc.hackedu.us because it's not backed up and isn't as battle tested as Google Sheets or LibreOffice Calc. What if we create a private repo, say `hackedu/private`, and have a LibreOffice Calc sheet in there? Ideally we'd have a TSV or CSV file, but we'll want to be able to have formulas in the sheet.

> So that's why I think Max should work on the general club in a box scalable solution instead of manually onboarding each club right now.

What about the idea of doing things that don't scale? Perhaps I could start taking these calls to onboard new clubs if @MaxWofford's time would be better spent elsewhere?

**Comment by MaxWofford** [comment] 2015-05-04 07:40
@zachlatta Right now we aren't giving our new clubs much value and we can't get much. This is mostly because it is the end of the school year, and most organizers who are starting new clubs are planning their first meetings for the next school year. Onboarding new clubs right now mostly adds inertia to the community.

One way to fix this might be to waitlist anyone starting their club next school year. This would be beneficial to clubs planning on doing stuff over the summer and the clubs that have already been started up who want to integrate with hackEDU.

**Comment by zachlatta** [comment] 2015-05-04 13:13
>One way to fix this might be to waitlist anyone starting their club
>next school year.

Love this idea. We could "onboard" them onto our waitlist. Essentially
we'd accept them into hackEDU, but defer the start of their "membership"
until next semester. Thoughts?

**Comment by MaxWofford** [comment] 2015-05-05 01:46
@jonleung?

**Comment by jonleung** [comment] 2015-05-06 03:46
@zachlatta @MaxWofford, let's discuss when you're back. I think a lot of this has to do with Max's new role / responsibilities! Can't wait!

**Comment by zachlatta** [comment] 2015-05-06 03:47
Can we have the discussion online here? Easier and I don't think this warrants an in-person discussion.

**Comment by jonleung** [comment] 2015-05-06 03:50
I think most efforts should be to focus on building club in a box. It
seemed as if onboarding was stressful for max and as such deviated focus.
Zach I think you expressed interest in onboarding. I think that's a good
idea
ᐧ


—
Sent from my mobile–apologies for brevity and any typos!

hackedu.us | 610-761-0083

**Comment by zachlatta** [comment] 2015-05-06 03:56
Yeah. @MaxWofford—what if I onboarded new clubs and just added them to a waitlist for us?

Also, bringing back something I said earlier.

> > @zachlatta I'm not sure about where we want the finalized version
> of this to go, but I'm planning on building it up in calc.hackedu and
> exporting csv to something else.
> 
> I'm not sure if I'm comfortable having this data in
> https://calc.hackedu.us because it's not backed up and isn't as battle
> tested as Google Sheets or LibreOffice Calc. What if we create a
> private repo, say `hackedu/private`, and have a LibreOffice Calc sheet
> in there? Ideally we'd have a TSV or CSV file, but we'll want to be able
> to have formulas in the sheet.

**Comment by jonleung** [comment] 2015-05-06 04:30
I think that having this on AirTable may be a good way to go. They just
gave us pro accounts! Huzzah @maxwofford

https://airtable.com
ᐧ


—
Sent from my mobile–apologies for brevity and any typos!

hackedu.us | 610-761-0083

**Comment by zachlatta** [comment] 2015-05-06 15:36
How can we use the free AirTable accounts? I'd like to try it out first
before committing to using it.

I'm hesitant to add another third-party system to our stack. What's
wrong with a LibreOffice Calc spreadsheet?

**Comment by MaxWofford** [comment] 2015-05-07 00:46
@zachlatta @jonleung Onboarding clubs isn't a big time investment on my part and I plan on to start abstracting the process to make it more efficient. My worry is that onboarding clubs immediately that aren't starting until after summer is an inefficient use of my time, because neither the applicants nor hackEDU will be getting anything immediately out of it.

@jonleung Happy to play with it, but AirTable doesn't have android support yet :/

**Comment by zachlatta** [comment] 2015-05-07 06:16
>My worry is that onboarding clubs immediately that aren't starting
>until after summer is an inefficient use of my time, because
>neither the applicants nor hackEDU will be getting anything
>immediately out of it.

Is this still a worry if we onboard them onto a waitlist for next
semester, as previously mentioned in this thread?

**Comment by MaxWofford** [comment] 2015-05-08 02:37
If they are onboarded now with nothing to do we may subtract from our community. Adding people who aren't actively working on something won't be contributing, which saps momentum.

Quick side-note: until this discussion has a resolution, I will be onboarding the same way from before the discussion.

**Comment by zachlatta** [comment] 2015-05-08 15:21
Agreed, good point. What if we talked with them and then added them to
our waitlist? So they're not yet part of the hackEDU network, but
they're on the list for the beginning of next semester.

**Comment by zachlatta** [comment] 2015-08-10 19:51
Alright. Update time.

I've primarily been handling club leader onboarding calls and been adding them to a waitlist we have in the AirTable. There are probably a couple entries I've missed and not added to the AirTable, but I have personal notes on all of them and will add them with due time.

Closing discussion for now!

**Closed by zachlatta** 2015-08-10 19:51 UTC
